[EXEC]
CONNECTSTR=Data Source=.;Initial Catalog=tks;Integrated Security=True;
SQLSTR=tksRiyu

[PARAM1]
NAME=bhtid
IO=INPUT
TYPE=varchar
;--定型6	BHTID

[PARAM2]
NAME=bhtdate 
IO=INPUT
TYPE=varchar
;--定型6	BHT日付

[PARAM3]
NAME=bhttime 
IO=INPUT
TYPE=varchar
;--定型6	BHT時間

[PARAM4]
NAME=syaincd
IO=INPUT
TYPE=varchar
;--定型6	社員CD

[PARAM5]
NAME=nonyudt
IO=INPUT
TYPE=varchar
;--定型6	納入日

[PARAM6]
NAME=hantei
IO=INPUT
TYPE=varchar
;--定型6	判定

[PARAM7]
NAME=kbn
IO=INPUT
TYPE=varchar
;--区分

[PARAM8]
NAME=result
IO=OUTPUT
TYPE=int
;--戻り値

[PARAM9]
NAME=msg
IO=OUTPUT
TYPE=varchar
;--メッセージ

