[EXEC]
CONNECTSTR=Data Source=POTSVR\SQLEXPRESS;Initial Catalog=tks;Integrated Security=False;User ID=sa;Password=manager
;CONNECTSTR=Data Source=.;Initial Catalog=tks;Integrated Security=True;
SQLSTR=tksLive

[PARAM1]
NAME=bhtid
IO=INPUT
TYPE=varchar
;--定型6	BHTID

[PARAM2]
NAME=bhtdate 
IO=INPUT
TYPE=varchar
;--定型6	BHT日付

[PARAM3]
NAME=bhttime 
IO=INPUT
TYPE=varchar
;--定型6	BHT時間

[PARAM4]
NAME=syaincd
IO=INPUT
TYPE=varchar
;--定型6	社員CD

[PARAM5]
NAME=nonyudt
IO=INPUT
TYPE=varchar
;--定型6	納入日

[PARAM6]
NAME=hantei
IO=INPUT
TYPE=varchar
;--定型6	判定


[PARAM7]
NAME=result
IO=OUTPUT
TYPE=int
;--戻り値

[PARAM8]
NAME=msg
IO=OUTPUT
TYPE=varchar
;--メッセージ

[PARAM9]
NAME=svdate
IO=OUTPUT
TYPE=varchar
;--日付

[PARAM10]
NAME=svtime
IO=OUTPUT
TYPE=varchar
;--時間
