[EXEC]
CONNECTSTR=Data Source=POTSVR\SQLEXPRESS;Initial Catalog=tks;Integrated Security=False;User ID=sa;Password=manager
;CONNECTSTR=Data Source=.;Initial Catalog=tks;Integrated Security=True;
SQLSTR=tksZkInq

[PARAM1]
NAME=bhtid
IO=INPUT
TYPE=varchar
;--’èŒ^6	BHTID

[PARAM2]
NAME=bhtdate 
IO=INPUT
TYPE=varchar
;--’èŒ^6	BHT“ú•t

[PARAM3]
NAME=bhttime 
IO=INPUT
TYPE=varchar
;--’èŒ^6	BHTŠÔ

[PARAM4]
NAME=syaincd
IO=INPUT
TYPE=varchar
;--’èŒ^6	ĞˆõCD

[PARAM5]
NAME=nonyudt
IO=INPUT
TYPE=varchar
;--’èŒ^6	”[“ü“ú

[PARAM6]
NAME=hantei
IO=INPUT
TYPE=varchar
;--’èŒ^6	”»’è

[PARAM7]
NAME=hno6
IO=INPUT
TYPE=varchar
;--}”Ô

[PARAM8]
NAME=zno16
IO=INPUT
TYPE=varchar
;--}”Ô

[PARAM9]
NAME=nyukosuu
IO=INPUT
TYPE=int
;--“ü”—Ê

[PARAM10]
NAME=syukosuu
IO=INPUT
TYPE=int
;--“ü”—Ê




[PARAM11]
NAME=result
IO=OUTPUT
TYPE=int
;--–ß‚è’l

[PARAM12]
NAME=msg
IO=OUTPUT
TYPE=varchar
;--ƒƒbƒZ[ƒW

[PARAM13]
NAME=zaikosuu
IO=OUTPUT
TYPE=int
;--İŒÉ”

